[workspace]
resolver = "2"
members = [
    "crates/attestations",
    "crates/rvlinux",
    "crates/wrapped-rustc-lib",
    "programs/fibonacci",
    "programs/hello-rustc",
    "programs/replay-rustc",
    "cli",
]

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
version = "0.1.0"

[workspace.dependencies]
attestations = { path = "crates/attestations" }

ed25519-dalek = { version = "2", default-features = false }
sha2          = { version = "0.10", default-features = false }
hkdf          = { version = "0.12", default-features = false }
serde         = { version = "1", default-features = false, features = ["derive"] }
serde_json    = "1"
hex           = { version = "0.4", default-features = false, features = ["alloc"] }
sgx-isa       = "0.4"
clap          = { version = "4", features = ["derive"] }
syn           = { version = "2", default-features = false, features = ["full", "parsing", "printing"] }
quote         = { version = "1", default-features = false }
proc-macro2   = { version = "1", default-features = false }
wasmi         = { version = "1" }
