[package]
name = "attestations"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
ed25519-dalek = { workspace = true, features = ["std"] }
sha2          = { workspace = true, features = ["std"] }
hkdf          = { workspace = true, features = ["std"] }
serde         = { workspace = true, features = ["std"] }
serde_json    = { workspace = true }
hex           = { workspace = true, features = ["std"] }
getrandom     = "0.2"

[target.'cfg(target_env = "sgx")'.dependencies]
sgx-isa = { workspace = true, features = ["sgxstd"] }
