[package]
name = "hello-rustc"
edition.workspace = true
license.workspace = true
version.workspace = true

[[bin]]
name = "hello-rustc"
path = "src/main.rs"

[dependencies]
attestations = { workspace = true }
serde_json   = { workspace = true }
hex          = { workspace = true, features = ["std"] }
