[package]
name = "run-and-verify"
edition.workspace = true
license.workspace = true
version.workspace = true

[[bin]]
name = "verify-envelope"
path = "src/main.rs"

[dependencies]
attest-core     = { workspace = true }
attest-registry = { workspace = true }
attest-verify   = { workspace = true }
serde_json      = { workspace = true }
hex             = { workspace = true, features = ["std"] }
